### ISSUE TITLE
Bug Report: Transcription result disappear instantly - Can't view results

### ISSUE THREAD

**Issue by dariushazimi** [awslabs/media-analysis-solution#17]
Transcription result disappears from the screen after briefly (1 sec ) being displayed.
Tested the frontend both on Chrome and Safari.
Same results with the code downloaded as of Sep 13.
`Chrome: Error: backend.js`
Failed to load resource: the server responded with a status of 400 ()
react-dom.production.min.js:164 DOMException: Failed to execute 'querySelector' on 'Document': '-4500-0f6ba24f-5f63-4f39-b3ec-xxxxxx' is not a valid selector.
    at m (https://xxxx.cloudfront.net/static/js/main.bbd56237.js:1:49498)
    at t.value (https://xxxx.cloudfront.net/static/js/main.bbd56237.js:1:109338)
    at commitLifeCycles (https://xxxxxx.cloudfront.net/static/js/main.bbd56237.js:1:542425)
    at t (https://xxxxx.cloudfront.net/static/js/main.bbd56237.js:1:546002)
    at w (https://xxxx.cloudfront.net/static/js/main.bbd56237.js:1:551484)
    at E (https://xxxxx.cloudfront.net/static/js/main.bbd56237.js:1:551185)
    at h (https://xxxx.cloudfront.net/static/js/main.bbd56237.js:1:550313)
    at d (https://xxxx.cloudfront.net/static/js/main.bbd56237.js:1:549703)
    at Object.enqueueSetState (https://xxxxxxx.cloudfront.net/static/js/main.bbd56237.js:1:524228)
    at t.o.setState (https://xxxxx.cloudfront.net/static/js/main.bbd56237.js:1:503510)

Any idea what the issue is? It used to work fine before July 2019.
Thanks

**Comment by tomnight** [comment]
A fix for this issue was posted in the last release, its was a issue with Elastic search and the version of the SDK being used in the demo site.  Can you try updating to version 1.3.2?

https://aws.amazon.com/solutions/media-analysis-solution/
